# examples/demo.py

import sys
# sys.path.append('..')

from vmp_transformer.src.api.transformer import VMPTransformer, transform_assembly_to_vmp

def example_simple_arithmetic():
    """Example: Simple arithmetic operations"""
    print("=== Example 1: Simple Arithmetic ===")
    
    assembly_code = """
    section .text
    main:
        mov eax, 10       ; Load 10 into eax
        mov ebx, 20       ; Load 20 into ebx
        add ecx, eax, ebx ; Add eax and ebx, store in ecx
        ret ecx           ; Return result
    """
    
    # Transform to VMP
    result = transform_assembly_to_vmp(assembly_code, debug=True)
    
    if 'error' not in result:
        print("Original Assembly:")
        print(assembly_code)
        print("\nVMP Protected Assembly:")
        print(result['vmp_assembly'])
        print(f"\nBytecode size: {result['metadata']['bytecode_size']} bytes")
        print(f"Variables: {result['metadata']['variables']}")
    else:
        print(f"Error: {result['error']}")

def example_loop():
    """Example: Loop with comparison"""
    print("\n=== Example 2: Loop ===")
    
    assembly_code = """
    section .text
    loop_start:
        mov ecx, 5        ; Counter
    loop_body:
        dec ecx           ; Decrement counter
        cmp ecx, 0        ; Compare with 0
        jne loop_body     ; Jump if not equal
        ret
    """
    
    result = transform_assembly_to_vmp(assembly_code)
    
    if 'error' not in result:
        print("Original Assembly:")
        print(assembly_code)
        print("\nVMP Protected Assembly:")
        print(result['vmp_assembly'])
    else:
        print(f"Error: {result['error']}")

def example_memory_operations():
    """Example: Memory operations"""
    print("\n=== Example 3: Memory Operations ===")
    
    assembly_code = """
    section .data
        buffer db 10, 20, 30, 40
        
    section .text
    main:
        mov eax, buffer   ; Load buffer address
        mov ebx, [eax]    ; Load first byte
        add eax, 1        ; Next byte
        mov ecx, [eax]    ; Load second byte
        add edx, ebx, ecx ; Add values
        ret edx
    """
    
    transformer = VMPTransformer(debug=False)
    result = transformer.transform_assembly(assembly_code)
    
    if 'error' not in result:
        print("Original Assembly:")
        print(assembly_code)
        print("\nVMP Protected Assembly (first 10 lines):")
        lines = result['vmp_assembly'].split('\n')
        for line in lines[:10]:
            print(line)
        if len(lines) > 10:
            print("...")
    else:
        print(f"Error: {result['error']}")

def example_batch_transform():
    """Example: Batch transformation"""
    print("\n=== Example 4: Batch Transformation ===")
    
    files = [
        ("add.asm", "mov eax, 5\nadd eax, 3\nret eax"),
        ("mul.asm", "mov eax, 4\nmov ebx, 6\nmul ecx, eax, ebx\nret ecx"),
        ("xor.asm", "mov eax, 0xFF\nxor eax, 0xAA\nret eax")
    ]
    
    transformer = VMPTransformer()
    results = transformer.batch_transform(files)
    
    for filename, result in results.items():
        print(f"\n{filename}:")
        if 'error' not in result:
            print(f"  Bytecode size: {result['metadata']['bytecode_size']} bytes")
            print(f"  Variables: {result['metadata']['variables']}")
        else:
            print(f"  Error: {result['error']}")

def example_advanced_vmp():
    """Example: Advanced VMP with analysis"""
    print("\n=== Example 5: Advanced VMP with Analysis ===")
    
    assembly_code = """
    section .text
    factorial:
        mov eax, 5        ; n = 5
        mov ebx, 1        ; result = 1
    fact_loop:
        cmp eax, 1        ; if n <= 1
        jle fact_done     ; goto done
        mul ebx, ebx, eax ; result *= n
        dec eax           ; n--
        jmp fact_loop     ; continue loop
    fact_done:
        ret ebx           ; return result
    """
    
    transformer = VMPTransformer(debug=True)
    result = transformer.transform_assembly(assembly_code)
    
    if 'error' not in result:
        print("Analyzing VMP bytecode...")
        
        # Analyze the generated bytecode
        analysis = transformer.analyze_vmp_code(result['bytecode'])
        
        if analysis['success']:
            print("\nExecution trace:")
            for trace_line in analysis['trace'][:10]:  # First 10 trace lines
                print(f"  {trace_line}")
            if len(analysis['trace']) > 10:
                print(f"  ... ({len(analysis['trace'])} total trace lines)")
        else:
            print(f"Analysis failed: {analysis['error']}")
    else:
        print(f"Error: {result['error']}")

def main():
    """Run all examples"""
    print("VMP Transformer Demo")
    print("===================\n")
    
    # example_simple_arithmetic()
    example_loop()
    # example_memory_operations()
    # example_batch_transform()
    # example_advanced_vmp()
    
    print("\n===================")
    print("Demo completed!")

if __name__ == "__main__":
    main()